[module/bspwm]
type = internal/bspwm

; =========================================================
; PURE DOT PAGER (NO WRAPPER)
; =========================================================

ws-icon-default = ●

; 1. FOCUSED workspace (chỉ đổi màu dot)
label-focused = ●
label-focused-foreground = #fa89b4
label-focused-background =
label-focused-padding = 1

; 2. OCCUPIED workspace
label-occupied = ●
label-occupied-foreground = #e1e6f5
label-occupied-background =
label-occupied-padding = 1

; 3. URGENT workspace
label-urgent = ●
label-urgent-foreground = #F38BA8
label-urgent-background =
label-urgent-padding = 1

; 4. EMPTY workspace (hidden)
label-empty =
label-empty-padding = 0