[module/date]
type = internal/date
interval = 1

date = %d/%m
date-alt = %A, %d %B %Y

time = %H:%M
time-alt = %H:%M:%S

; Đổi màu icon đồng hồ để đồng bộ với các icon bên phải
format-prefix = " "
format-prefix-foreground = ${colors.primary}

label = %time%  |  %date%