[module/kew]
type = custom/script

; Lấy Tên bài hát và Nghệ sĩ
exec = playerctl -p kew metadata --format "  {{title}} - {{artist}}"
interval = 1

; Chỉ hiển thị module trên bar khi kew đang được mở
exec-if = playerctl -p kew status 2>/dev/null

; Kế thừa màu primary từ file config chính
format = 
format-foreground = ${colors.primary}

; Cắt chuỗi nếu tên bài hát quá dài (tránh đẩy lệch các module khác)
label = %output:0:35:...%

; Các thao tác chuột trực tiếp lên text trên bar
click-left = playerctl -p kew play-pause
click-right = playerctl -p kew next
click-middle = playerctl -p kew previous
scroll-up = playerctl -p kew volume 0.05+
scroll-down = playerctl -p kew volume 0.05-