[module/power]
type = custom/text

; Đã xóa khoảng trắng thừa ở cuối icon
content = ""

; Ép padding về 0 để không tạo khoảng trống dư thừa
content-padding = 0

content-foreground = #F38BA8

; ĐỔI LỆNH TẠI ĐÂY: Trỏ chuột trái sẽ gọi Rofi menu
click-left = ~/.local/bin/powermenu.sh

; Giữ nguyên chuột phải để reboot nhanh nếu cần
click-right = systemctl reboot