[colors]
background = #16181a
foreground = #FFFFFFFF
primary = #89B4FA
border = #30FFFFFF
[bar/island]
; Tăng chiều rộng lên 45% (tùy ý chỉnh)
width = 78%
height = 60

; Tính toán offset-x để căn giữa: (100% - width) / 2
; Ở đây: (100 - 78) / 2 = 11%
offset-x = 11%
offset-y = 12

radius = 20
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}
border-color = ${colors.border}

line-size = 3
border-size = 1

padding-left = 2
padding-right = 3
module-margin = 1

font-0 = "JetBrainsMono Nerd Font:size=11;3"
; Thêm font icon nếu cần
font-1 = "JetBrainsMono Nerd Font:size=13;4"

enable-ipc = true
; wm-restack = bspwm

; Cho phép bar floating hoàn toàn
override-redirect = true

modules-left = power user wifi cpu mic-status kew
modules-center = bspwm
modules-right = gpu pulseaudio battery date

include-file = ~/.config/polybar/modules/bspwm.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/battery.ini
include-file = ~/.config/polybar/modules/audio.ini
include-file = ~/.config/polybar/modules/user.ini
include-file = ~/.config/polybar/modules/power.ini
include-file = ~/.config/polybar/modules/wifi.ini
include-file = ~/.config/polybar/modules/hw_mic.ini
include-file = ~/.config/polybar/modules/kew.ini