WHEEL_UP    add volume 2     # Lăn chuột lên tăng âm lượng
WHEEL_DOWN  add volume -2    # Lăn chuột xuống giảm âm
UP          add volume 5     # Mũi tên lên tăng 5%
DOWN        add volume -5
RIGHT       seek 5           # Tua tới 5 giây
LEFT        seek -5
f           cycle fullscreen # Bật/tắt toàn màn hình
q           quit             # Thoát
