# Hiển thị
border=no                 # Tắt thanh tiêu đề (tương thích hoàn hảo với bspwm)
keep-open=yes             # Video chạy xong sẽ tạm dừng ở khung hình cuối, không tự tắt
autofit-larger=80%x80%    # Kích thước cửa sổ tối đa khi mở video cục bộ
geometry=50%:50%          # Mở ở ngay giữa màn hình

# Tối ưu hóa phần cứng & Chất lượng
profile=gpu-hq            # Chất lượng render cao nhất
hwdec=vaapi          # Tự động dùng Intel UHD hoặc NVIDIA để giải mã video
vo=gpu                    # Video Output qua GPU
# Tắt Vulkan (vì chính nó đang gây treo trên máy bạn)
gpu-context=x11egl

# Tinh chỉnh UI (On-Screen Controller)
osd-bar=no                # Tắt thanh tiến trình mặc định xấu xí
osd-font="JetBrainsMono Nerd Font"
osd-font-size=30
osd-color="#cdd6f4"       # Màu text Catppuccin
osd-border-color="#1e1e2e"


# --- TỐI ƯU CHO PHÁT TỐC ĐỘ CAO ---
# Ưu tiên audio để tránh bị ngắt đoạn
video-sync=audio

# Tăng buffer để tải trước nhiều hơn
cache=yes
demuxer-max-bytes=1GiB

# Tối ưu audio scaletempo
af=scaletempo=stride=20:overlap=0.6:search=10

# Bỏ qua các hiệu ứng render video nặng khi đang tua nhanh
# (Giúp NVIDIA không phải làm việc quá tải khi speed > 2x)
[speed-high]
profile-cond=speed > 1.5
hwdec=nvdec-copy
vo=gpu
video-sync=audio